<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1010a0b68656c6c6f2e70726f746f120568656c6c6f221f0a0c48656c" .
            "6c6f52657175657374120f0a076d657373616765180120012809222f0a0d" .
            "48656c6c6f526573706f6e7365120f0a076d657373616765180120012809" .
            "120d0a0576616c696418022001280532410a0548656c6c6f12380a096865" .
            "6c6c6f5f61706912132e68656c6c6f2e48656c6c6f526571756573741a14" .
            "2e68656c6c6f2e48656c6c6f526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

