<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto

namespace GPBMetadata;

class PBEcho
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3010a0a6563686f2e70726f746f12046563686f221e0a0b4563686f52" .
            "657175657374120f0a076d657373616765180120012809222e0a0c456368" .
            "6f526573706f6e7365120f0a076d657373616765180120012809120d0a05" .
            "76616c696418022001280532370a044563686f122f0a046563686f12112e" .
            "6563686f2e4563686f526571756573741a122e6563686f2e4563686f5265" .
            "73706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

